CREATE TABLE Billett(
    id INTEGER AUTO_INCREMENT NOT NULL,
    Film VARCHAR(255) NOT NULL,
    Antall INTEGER NOT NULL,
    Fornavn VARCHAR(255) NOT NULL,
    Etternavn VARCHAR(255) NOT NULL,
    Telefonnr VARCHAR(255) NOT NULL,
    Epost VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);